version: "3"

services:
  meta:
    build: .
    command: cron
    volumes:
      - "./caches:/app/caches"
      - "./upstream:/app/upstream"
      - "./launcher:/app/launcher"
      - "./public:/app/public"
      - "./config:/app/config"
    restart: unless-stopped
